### ISSUE TITLE
Sketch the interface

### ISSUE THREAD

**Issue by lornajane** [ibm-cds-labs/sodashboard#1]
Show how the list view should be laid out, including search controls.  From the requirements documentation this should include:

Fields from Stackoverflow:
 - question title (and a way to get to the question on stackoverflow)
 - asker username (and a way to view their profile on stackoverflow)
 - date asked
 - tags

Our own data fields:
 - status (new, in progress, delegated, answered) (and ability to change)
 - assigned to a user (and ability to change)
 - hidden (and ability to change)

**Comment by isc-rsingh** [comment]
<img width="1144" alt="so_mockup_v4" src="https://cloud.githubusercontent.com/assets/3768695/25045225/308b9416-20f9-11e7-9d49-19e696af0bf2.png">

**Comment by isc-rsingh** [comment]
the eyeball icon hides the question for the logged-in user

**Comment by isc-rsingh** [comment]
New mockup showing number of answers .

<img width="972" alt="so_mockup_v5" src="https://cloud.githubusercontent.com/assets/3768695/25098647/5b4b3f78-2377-11e7-9af6-3465435ea9a1.png">

**Comment by ptitzler** [comment]
What kind of additional filters are you planning to provide (1) and what are the default display settings (2) for the list? 

(1) by state, assigned to the logged-in user, age, ...
(2) As a monitor I'd probably want to have all answered questions hidden (no action is required after all), the most current question listed on top, etc etc.

**Comment by lornajane** [comment]
This looks good to me, is it valuable to add a snippet from the question body or should we click through for that do you think?  I also think that the eyeball should hide for everyone, we probably want to all have the same data visible that we're working on, just with filtering and ordering options.

I tried to keep the various filtering questions into separate issues so that we can iterate on what we're building and maybe answer these questions as we go along.

**Comment by ptitzler** [comment]
Is there a specific use case that requires hiding a question other than the one where a (correct) answer wasn't accepted? We might not need this feature if the agreement is that it is okay to mark a question as accepted. (Regular filters would hide such a question).

**Comment by lornajane** [comment]
Maybe the question doesn't apply to us?  It's in a context that doesn't make sense for us, or the question is nonsense, or is mistagged, or we otherwise just don't feel we need to respond.  I don't think it makes sense to mark questions as accepted if they are not in case we want to report on that data later.

**Comment by ptitzler** [comment]
Okay, that makes sense.

**Comment by isc-rsingh** [comment]
![ui_sketch_2017_07_14](https://user-images.githubusercontent.com/3768695/28323401-acd50e42-6ba6-11e7-9bed-2ca815ec1e87.png)

**Comment by isc-rsingh** [comment]
I’ve checked in my UI mockup to the `ui2` branch. You can see it by manually going to ui.html in your browser, e.g. http://localhost:6014/ui.html

The data is static, so no buttons will do anything, but you can click on the Questions drop-down or the Tags button (doesn’t look like a button yet--just the word ‘Tags’) to see what’s going on.
