### ISSUE TITLE
Searching for rejected questions

### ISSUE THREAD

**Issue by lornajane** [ibm-cds-labs/sodashboard#103]
@mikebroberg reported that when searching to include "answered and rejected" questions (that he had assigned to another user), he wasn't able to find a ticket that he'd seen earlier in the day.  The ticket had been rejected, but should still show up in the search.

Tip from @glynnbird:
```
just FYI the search happens on the client side in PouchDB. Here's the code that generates the Mango query depending on what is supplied in the search form https://github.com/ibm-watson-data-lab/sodashboard/blob/master/public/js/sodashboard.js#L611-L684 . It looks like it takes `rejected` and `answered` into account at a glance.
```

The first step is to replicate the problem and confirm if this is happening.

**Comment by glynnbird** [comment]
Just tried to reproduce this by searching for "Evaluation error" with Owner=all and the "Rejected" tick box ticked and it worked! i.e 48409135 was in the result set

![screen shot 2018-01-26 at 10 47 35](https://user-images.githubusercontent.com/697925/35436475-83e82146-0286-11e8-8d00-21f229a56a3d.png)

**Comment by lornajane** [comment]
Closing for now since we can't reproduce but please re-open if you have more info
