### ISSUE TITLE
Migrate permissions from existing database to events database 

### ISSUE THREAD

**Issue by glynnbird** [ibm-cds-labs/sodashboard#108]
As a one-off task, Cloudant users who have access to the existing sodashboard database will also need access to the new "events" database. (see issue #105)

- work out how to move Cloudant permissions from one database to another
- write a shell script that can do it
- run it!

**Comment by glynnbird** [comment]
done in #105

**Comment by lornajane** [comment]
Script run, issue can close (thanks!)
