### ISSUE TITLE
Assign button is disabled

### ISSUE THREAD

**Issue by lornajane** [ibm-cds-labs/sodashboard#114]
When I want to assign a question to someone, I see the dropdown of people but the assign button remains disabled until I choose "other", and start typing.  Then I can pick anyone from the list and assign successfully.

**Comment by vabarbosa** [comment]
the issue here appears to be a check for user id length of 9 characters. if your test user IDs are not 9 character the button does not get enabled.

**Comment by vabarbosa** [comment]
PR #115 has been submitted to just check for non-empty user id instead of exactly 9 characters
