### ISSUE TITLE
Database of user expertise/tags

### ISSUE THREAD

**Issue by isc-rsingh** [ibm-cds-labs/sodashboard#18]

**Comment by vabarbosa** [comment]
@rajrsingh we currently have a team database (which powers https://ibm-cds-labs.github.io/team) and contains expertise info, etc. we may need to update it and additional info but couldn't we possibly access/incorporate that database rather that creating a new db?

**Comment by ptitzler** [comment]
I would suggest not adding an external dependency because that will make it much harder for a third-party to adopt the SO tooling without making any changes.

**Comment by isc-rsingh** [comment]
Point taken @ptitzler but I don't want to sacrifice what makes sense for us to make the tool more generic. How about we set a flag to either use the stackexchange API to get the user's active tags (e.g. /2.2/users/2683818/tags?order=desc&sort=popular&site=stackoverflow) or to use a custom API? Can we modularize our custom solution?

**Comment by mmcelaney** [comment]
Should we move this part of Task #25 to this card/task?? We should try to take advantage of the stats that are already collected and exposed on the SO page. 
"For example, this link http://stackoverflow.com/search?q=user:5244530+[cloudant] displays my activity related to Cloudant questions. The user profile could expose those links for the tags that are being monitored by `soingest`"

**Comment by mmcelaney** [comment]
We did remove that part of the task from #25 and make decisions about that workflow here.

**Comment by lornajane** [comment]
Agreed to move forward by tagging users with topic tags of their choice - see epic #70
