### ISSUE TITLE
Document persisted data structures in wiki

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/sodashboard#21]
We need to document the document types that we are storing in the repository database.

**Comment by ptitzler** [comment]
https://github.com/ibm-cds-labs/sodashboard/wiki/Repository-document-structures

**Comment by glynnbird** [comment]
I've added some fields to that wiki document @ptitzler. It makes the example document a bit strange i.e. it is assigned, rejected AND answered (!) but at least it has one of everything. I've added custom_tags to it too which is a new thing.

**Comment by ptitzler** [comment]
Yup. What we would really need to document is the schema definition :frowning_face:

**Comment by lornajane** [comment]
Do we need to do more here, or is this enough information for our current data structure?  I'm not sure if I should move this forward or not.
