### ISSUE TITLE
Sync errors are not communicated to the end user

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/sodashboard#22]
CORS was accidentally disabled in the new Cloudant instance. When I opened the SOdashboard no SO data was displayed. Since it usually takes about 10 seconds for the load to complete I started to investigate after a little while by inspecting the network traffic. I discovered that a call to the Cloudant REST API returned error 401, indicating that the credentials were invalid. After CORS was enabled in Cloudant things worked as expected. We need to somehow critical expose sync issues to the end user.

**Comment by mmcelaney** [comment]
@vabarbosa will fu with @glynnbird on squashing this bug.

**Comment by ptitzler** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/afc93986-3917-48ae-8901-f070f6d109f7 "green-blue-toolchain-20170516074606603"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/5ea1a679-3a40-49d5-9621-b48806ab22cc "green-blue-toolchain-20170516074606603") deployed [sodashboard](https://github.com/ibm-cds-labs/sodashboard/releases/tag/deploy-ibm-yp-us-south-ptitzler_org-dev-20170621-073356 "deploy-ibm-yp-us-south-ptitzler_org-dev-20170621-073356") to [dev](https://console.bluemix.net/apps/0afef81b-20fa-4291-8439-a315f7beb7c9?env_id=ibm:yp:us-south "ibm:yp:us-south:ptitzler_org:dev"), including commit 53c7b2114af981f0179c115a8730f731b6a98dc5

**Comment by ptitzler** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/bb9178ab-039a-4b1b-bdfa-c5ab8e217c77 "sodashboard-wdp-infra"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/592bddce-9340-4b45-9afa-14c722dd7005 "sodashboard-wdp-infra") deployed [sodashboard](https://github.com/ibm-cds-labs/sodashboard/releases/tag/deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170621-073357 "deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170621-073357") to [wdp-infrastructure](https://console.bluemix.net/apps/1a72a47a-5417-4472-a928-23c0234b2dc9?env_id=ibm:yp:us-south "ibm:yp:us-south:Dev-Advocates:wdp-infrastructure"), including commit 53c7b2114af981f0179c115a8730f731b6a98dc5

**Comment by glynnbird** [comment]
I accidentally pushed the fix for this to the master, so now it's live without a review. 

The sync error detection was actually already in the code, but it was displaying an icon that didn't exist. I've swapped this out for a red danger sign.

I thought about showing an alert with the error message but his is actually already console.logged to the console if we're interested. If you switch off your wifi, you *can* keep using sodashboard because you're working with a local PouchDB database.
