### ISSUE TITLE
Create a frontend we can log into

### ISSUE THREAD

**Issue by lornajane** [ibm-cds-labs/sodashboard#3]
The users on our team will need to be able to log in so we know who they are.  We will also need to know who they are on stackoverflow (so we can link them to their questions/achievements) and on slack (so we can notify them of changes they should know about).

**Comment by glynnbird** [comment]
In the `ibm-cloudplatform` Slack, you can now type `/sodashboard` to get a link that allows you to log into our Dashboard. This creates your user profile and gives you access to a PouchDB/Cloudant app.
