### ISSUE TITLE
Add option for "Other" in Assign To dropdown

### ISSUE THREAD

**Issue by mmcelaney** [ibm-cds-labs/sodashboard#30]
When we send a question so someone outside of our team there should be a way for us to indicate this in the tool. Essentially in these cases, the ticket has been assigned to any number of people outside the team, and by assigning it to "Other" it will no longer show up in the "unnassigned" dashboard.

**Comment by vabarbosa** [comment]
**Other** option has been added (with additional input field to enter a name). see pr #41

**Comment by vabarbosa** [comment]
addressed in pr #41
