### ISSUE TITLE
Hitting the POST /slack endpoint hangs

### ISSUE THREAD

**Issue by glynnbird** [ibm-cds-labs/sodashboard#35]
If you hit the POST /slack endpoint with incorrect credentials, the socket is never closed and the connection hangs.

**Comment by ptitzler** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/afc93986-3917-48ae-8901-f070f6d109f7 "green-blue-toolchain-20170516074606603"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/5ea1a679-3a40-49d5-9621-b48806ab22cc "green-blue-toolchain-20170516074606603") deployed [sodashboard](https://github.com/ibm-cds-labs/sodashboard/releases/tag/deploy-ibm-yp-us-south-ptitzler_org-dev-20170524-144128 "deploy-ibm-yp-us-south-ptitzler_org-dev-20170524-144128") to [dev](https://console.ng.bluemix.net/apps/78a5108d-ade5-4fb7-ae89-ba14cb202784?env_id=ibm:yp:us-south "ibm:yp:us-south:ptitzler_org:dev"), including commits 8ad5ec7244219e5d62f48f2a8ee5dfb51123486f, fd08cae93c0535481c8443d878ab47597b9d989e

**Comment by ptitzler** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/bb9178ab-039a-4b1b-bdfa-c5ab8e217c77 "sodashboard-wdp-infra"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/592bddce-9340-4b45-9afa-14c722dd7005 "sodashboard-wdp-infra") deployed [sodashboard](https://github.com/ibm-cds-labs/sodashboard/releases/tag/deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170524-144154 "deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170524-144154") to [wdp-infrastructure](https://console.ng.bluemix.net/apps/af64bba7-770f-4666-bad7-4dd3377e551d?env_id=ibm:yp:us-south "ibm:yp:us-south:Dev-Advocates:wdp-infrastructure"), including commits 8ad5ec7244219e5d62f48f2a8ee5dfb51123486f, fd08cae93c0535481c8443d878ab47597b9d989e
