### ISSUE TITLE
normalize custom tags

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/sodashboard#37]
One general challenge when using tags is that different users might use variations of the same tag name, which makes analysis much more difficult. For example, a question might be tagged with `Java`,  `java`, `Java_ ` (note the trailing space) or `Java8`. Case insensitive auto-suggestions combined with basic string normalization should reduce the likelihood of ending up with too many semantically identical tags.

**Comment by vabarbosa** [comment]
custom tags have been updated (see pr #41)
- trimmed
- lowercased
- replaced whitespace hyphen
- remove empty tag strings
- remove duplicate tags (in the same question)

**Comment by vabarbosa** [comment]
@ptitzler regarding case-insensitive auto suggestion, can you clarify? do you mean having an autocomplete input field (for the custom tags) and using all existing/known tags (or custom tags) across all available questions to feed the autocomplete suggestions?

**Comment by ptitzler** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/bb9178ab-039a-4b1b-bdfa-c5ab8e217c77 "sodashboard-wdp-infra"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/592bddce-9340-4b45-9afa-14c722dd7005 "sodashboard-wdp-infra") deployed [sodashboard](https://github.com/ibm-cds-labs/sodashboard/releases/tag/deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170613-180006 "deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170613-180006") to [wdp-infrastructure](https://console.ng.bluemix.net/apps/e692976d-eb9a-4209-bee3-b89c4de4b384?env_id=ibm:yp:us-south "ibm:yp:us-south:Dev-Advocates:wdp-infrastructure"), including commit 45bb94c7b0ac651d9debe9fb1ede68e30c0b771e

**Comment by ptitzler** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/afc93986-3917-48ae-8901-f070f6d109f7 "green-blue-toolchain-20170516074606603"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/5ea1a679-3a40-49d5-9621-b48806ab22cc "green-blue-toolchain-20170516074606603") deployed [sodashboard](https://github.com/ibm-cds-labs/sodashboard/releases/tag/deploy-ibm-yp-us-south-ptitzler_org-dev-20170613-180038 "deploy-ibm-yp-us-south-ptitzler_org-dev-20170613-180038") to [dev](https://console.ng.bluemix.net/apps/fb79957e-a96e-45dd-b5da-eb553ce7f047?env_id=ibm:yp:us-south "ibm:yp:us-south:ptitzler_org:dev"), including commit 45bb94c7b0ac651d9debe9fb1ede68e30c0b771e
