### ISSUE TITLE
If a question has an accepted answer retire it

### ISSUE THREAD

**Issue by isc-rsingh** [ibm-cds-labs/sodashboard#42]
If a question has an accepted answer the system should automatically retire it

**Comment by vabarbosa** [comment]
@rajrsingh by retire you mean it shouldnt appear in the **Unassigned** or **Mine** view? or does retire include other special processing for the question?

**Comment by isc-rsingh** [comment]
@vabarbosa yes don't show it either of those views

**Comment by ptitzler** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/bb9178ab-039a-4b1b-bdfa-c5ab8e217c77 "sodashboard-wdp-infra"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/592bddce-9340-4b45-9afa-14c722dd7005 "sodashboard-wdp-infra") deployed [sodashboard](https://github.com/ibm-cds-labs/sodashboard/releases/tag/deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170609-161146 "deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170609-161146") to [wdp-infrastructure](https://console.ng.bluemix.net/apps/c126d148-d7e3-495f-b535-8611e1ef8b6c?env_id=ibm:yp:us-south "ibm:yp:us-south:Dev-Advocates:wdp-infrastructure"), including commit 4ebf0a390c561eb3c800af09c3092e7b819cb4e8

**Comment by ptitzler** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/afc93986-3917-48ae-8901-f070f6d109f7 "green-blue-toolchain-20170516074606603"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/5ea1a679-3a40-49d5-9621-b48806ab22cc "green-blue-toolchain-20170516074606603") deployed [sodashboard](https://github.com/ibm-cds-labs/sodashboard/releases/tag/deploy-ibm-yp-us-south-ptitzler_org-dev-20170609-161154 "deploy-ibm-yp-us-south-ptitzler_org-dev-20170609-161154") to [dev](https://console.ng.bluemix.net/apps/a64b77de-5559-4923-972e-ee53ce2f66c7?env_id=ibm:yp:us-south "ibm:yp:us-south:ptitzler_org:dev"), including commit 4ebf0a390c561eb3c800af09c3092e7b819cb4e8
