### ISSUE TITLE
Allow unassigning issues

### ISSUE THREAD

**Issue by lornajane** [ibm-cds-labs/sodashboard#50]
We can assign an issue, but we need to be able to unassign it too

**Comment by vabarbosa** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/bb9178ab-039a-4b1b-bdfa-c5ab8e217c77 "sodashboard-wdp-infra"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/592bddce-9340-4b45-9afa-14c722dd7005 "sodashboard-wdp-infra") deployed [sodashboard](https://github.com/ibm-watson-data-lab/sodashboard/releases/tag/deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170630-172032 "deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170630-172032") to [wdp-infrastructure](https://console.bluemix.net/apps/98495352-6297-45b1-afc8-74125781677b?env_id=ibm:yp:us-south "ibm:yp:us-south:Dev-Advocates:wdp-infrastructure"), including commit 1725ba0c8c7f2c0c4706ff20bd682c8f1a039ebd

**Comment by terichadbourne** [comment]
@vabarbosa I think Issue #86 may be related to this one.
