### ISSUE TITLE
Allow filtering of questions by tag

### ISSUE THREAD

**Issue by lornajane** [ibm-cds-labs/sodashboard#52]
(this needs to be in combination with other filters)

Allow a user to select none, one, or many tags to filter on so that they can restrict the results (we will search on a larger number of keywords once we have this, so people need to be able to reduce the amount of trees they see)

**Comment by lornajane** [comment]
Before we build this: do we want AND or OR filters?  Or both?  How possible is this with a cloudant backend?

**Comment by isc-rsingh** [comment]
sounds perfect for Cloudant Search / Lucene

**Comment by vabarbosa** [comment]
PR #95

**Comment by terichadbourne** [comment]
@vabarbosa @glynnbird @rajrsingh I think most of our UI work for basic filtering has been merged already. Should we be updating this issue to be just about adding an option to choose "AND" or "OR" as @lornajane suggested? Unless it changed while I was out, I think everything is currently "OR."  I can see a use case for wanting "AND" so you can find, for example PouchDB + Service Workers as a proxy for Offline First.
