### ISSUE TITLE
Prevent Vue.js artefacts displaying on page-load

### ISSUE THREAD

**Issue by glynnbird** [ibm-cds-labs/sodashboard#57]
When the sodashboard page first loads, you see a glimpse of the placeholder markers that are used by Vue.js in the HTML e.g.

 {{ somestring }}

This can be avoided by using the [v-cloak](https://vuejs.org/v2/api/#v-cloak) directive, which hides sections of the page until Vue.js has started up.

**Comment by vabarbosa** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/bb9178ab-039a-4b1b-bdfa-c5ab8e217c77 "sodashboard-wdp-infra"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/592bddce-9340-4b45-9afa-14c722dd7005 "sodashboard-wdp-infra") deployed [sodashboard](https://github.com/ibm-watson-data-lab/sodashboard/releases/tag/deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170705-111134 "deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170705-111134") to [wdp-infrastructure](https://console.bluemix.net/apps/3db13ed4-8b92-4453-bb21-d940ad7f8a35?env_id=ibm:yp:us-south "ibm:yp:us-south:Dev-Advocates:wdp-infrastructure"), including commit 790ebc953c4eabfde40b80b1002806e89f9c04a2
