### ISSUE TITLE
Allow users to tag themselves with topics

### ISSUE THREAD

**Issue by lornajane** [ibm-cds-labs/sodashboard#71]
We have questions tagged "Cloudant", "redis", "bluemix" and so on.  Add a way for users to tag themselves in their profile, either picking from an existing list or typing new tags.  We'll use this to link people with questions in their areas of interest/expertise.

**Comment by vabarbosa** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/bb9178ab-039a-4b1b-bdfa-c5ab8e217c77 "sodashboard-wdp-infra"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/592bddce-9340-4b45-9afa-14c722dd7005 "sodashboard-wdp-infra") deployed [sodashboard](https://github.com/ibm-watson-data-lab/sodashboard/releases/tag/deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170713-172053 "deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170713-172053") to [wdp-infrastructure](https://console.bluemix.net/apps/bf927c30-0582-4745-8fd0-97eb4e217fde?env_id=ibm:yp:us-south "ibm:yp:us-south:Dev-Advocates:wdp-infrastructure"), including commits f4355d8c42e26aa4bea40275c69c8e8b21382806, 4af238e968df10825e4b1293e004f42069f2c8ff
