### ISSUE TITLE
Find users linked to this topic tag

### ISSUE THREAD

**Issue by lornajane** [ibm-cds-labs/sodashboard#72]
When a question has tags associated with it, a user should be able to see which users have this tag listed in their profiles.  This is to allow us to know which of the team have knowledge about a particular technology or topic if we're looking for someone to help on a particular question.

**Comment by terichadbourne** [comment]
Can we both: 
- Show next to the name the matching tags the person has (so I'd know if it's one or multiple)
- Sort results by highest match
- Show real name, not username, of people in list

**Comment by vabarbosa** [comment]
@lornajane @rajrsingh, do you know if the new ui will be in place soon? if so, i think we should take @terichadbourne comments into account in the new ui and no need to make updates now. however, if it is still a some time away we should definitely include the changes in the current version.

**Comment by isc-rsingh** [comment]
Getting sick messed up my schedule @vabarbosa but I hope to put the new UI in place by end of next week.
