### ISSUE TITLE
Remove fake user records from real "assign to" and "matching tags" views 

### ISSUE THREAD

**Issue by terichadbourne** [ibm-cds-labs/sodashboard#81]
When I'm doing duty, the "Assign to" dropdown shows people we don't know. It's been brought to my attention that these are fake users, rather than people from other teams, so they need to be taught not to show up in dropdowns on the real interface. 

This will also affect the place where it pulls up results with matching tags.

**Comment by vabarbosa** [comment]
users records have been cleaned up in the cloudant db.
