### ISSUE TITLE
Hide "Show/Hide Notes" button (& symbol key?) when there are no docs to display

### ISSUE THREAD

**Issue by terichadbourne** [ibm-cds-labs/sodashboard#85]
In the miraculous circumstance in which there are no documents to display in the view (in this case no unassigned docs), there's no need to see the Show/Hide Notes button, so we should hide it when the number of docs listed is zero. 

We could do the same for the symbol key (which is in a PR waiting to be merged, not yet in the master). 

This can be done by adding a hidden class for both elements that's toggled on when the count of results to display = 0 and off otherwise.

![image](https://user-images.githubusercontent.com/19171465/28475400-fc172b3c-6e19-11e7-8c6b-bcdeb6ba3709.png)

**Comment by terichadbourne** [comment]
Makes sense to wait on this until after the filtering redesign, since the proposed hiddenness depends on those filters.

**Comment by vabarbosa** [comment]
@terichadbourne are you satisfied with the update we did as part of PR #95 where we disabled the button instead of hide? if so, mind closing this issue?

**Comment by terichadbourne** [comment]
@vabarbosa I'm totally satisfied with the state of the Show/Hide/No Notes button. 

The other part I'd mentioned here was that we could hide the symbols that show what accepted/rejected indicators look like when we weren't showing anything accepted or rejected. But it might actually be somewhat helpful for it to be there so you understand that nothing you're looking at is that way.

So yes, I'm good with this and closing it now. :)
