### ISSUE TITLE
Correct Assigned/Unassigned button label when editing Other details

### ISSUE THREAD

**Issue by terichadbourne** [ibm-cds-labs/sodashboard#86]
I just tried assigning a ticket to Other, but when I click on Other, the “Assign” button disables itself to force me to fill in the blank re who I’m assigning it to, and then as soon as I type one character the button changes to “Unassign,” so it appears there’s never an option to enter a name and then hit Assign or save it. I’ve tried just hitting the back arrow to get out of the Edit screen, but If I refresh the Unassigned list this ticket is still there, which leads me to believe that the assignment failed.

Update: Lorna tried the same but actually clicked on the "Unassign" button and it turned out to have the functionality of Assigning (which we know because the ticket left the Unassigned view), so it's actually an issue with what triggers the label to change rather than the actual functionality of the button.

![image](https://user-images.githubusercontent.com/19171465/28533986-04a579fc-706d-11e7-8ce3-d9619df1b4c6.png)

**Comment by vabarbosa** [comment]
Bluemix [toolchain](https://console-regional.ng.bluemix.net/devops/toolchains/bb9178ab-039a-4b1b-bdfa-c5ab8e217c77 "sodashboard-wdp-infra"): [Delivery Pipeline](https://console-regional.ng.bluemix.net/devops/pipelines/592bddce-9340-4b45-9afa-14c722dd7005 "sodashboard-wdp-infra") deployed [sodashboard](https://github.com/ibm-watson-data-lab/sodashboard/releases/tag/deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170818-132847 "deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170818-132847") to [wdp-infrastructure](https://console.bluemix.net/apps/1305070e-1bb3-401a-a9c3-14789c352e65?env_id=ibm:yp:us-south "ibm:yp:us-south:Dev-Advocates:wdp-infrastructure"), including commits 5a7df488dbb98bd12d5134429de7c703c5deec76, a5145c9c337d1153375e32eadf7d58057b97fd75
