### ISSUE TITLE
Make login status show correctly when using URL directly to dashboard

### ISSUE THREAD

**Issue by terichadbourne** [ibm-cds-labs/sodashboard#87]
If I have used Slack to log in and have one Chrome tab open successfully to the dashboard (proving I'm indeed logged in), and then in a new tab I just type in https://sodashboard.mybluemix.net/ , that new window tells me I'm not logged in. Need to find a way to make all new tabs know I'm already logged in. 

![image](https://user-images.githubusercontent.com/19171465/28577838-e3efe4ea-7125-11e7-8c92-47cecd03d23e.png)

**Comment by glynnbird** [comment]
Thanks @terichadbourne. At the moment, the home page is a dumb static page. It isn't checking whether you are logged in - it just points to the place where you can login.

This can be changed, of course. All I need to do is make this page 

- create a PouchDB object
- if there is a `_local/user` document, bounce the browser to home.html

**Comment by vabarbosa** [comment]
Bluemix [toolchain](https://console-regional.ng.bluemix.net/devops/toolchains/bb9178ab-039a-4b1b-bdfa-c5ab8e217c77 "sodashboard-wdp-infra"): [Delivery Pipeline](https://console-regional.ng.bluemix.net/devops/pipelines/592bddce-9340-4b45-9afa-14c722dd7005 "sodashboard-wdp-infra") deployed [sodashboard](https://github.com/ibm-watson-data-lab/sodashboard/releases/tag/deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170822-152427 "deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170822-152427") to [wdp-infrastructure](https://console.bluemix.net/apps/acd5223b-a505-4e05-b428-674a3f93e07b?env_id=ibm:yp:us-south "ibm:yp:us-south:Dev-Advocates:wdp-infrastructure"), including commits a571bd5ed778ab410c60fa60d84e0b7f0d279c6e, cba75258b319b03004cb54bb73c58fe241087d56
