### ISSUE TITLE
Update User's SO Profile to Activity Summary Tab

### ISSUE THREAD

**Issue by mmcelaney** [ibm-cds-labs/sodashboard#92]
Update user's SO profile from http://stackoverflow.com/users/5244530/ptitzler to link to the activity summary tab http://stackoverflow.com/users/5244530/ptitzler?tab=topactivity because it provides the most useful information.

![screen shot 2017-08-16 at 6 00 36 pm](https://user-images.githubusercontent.com/4404929/29387174-e2c73a76-82ac-11e7-9834-b516cd408bb7.png)

![screen shot 2017-08-16 at 6 02 46 pm](https://user-images.githubusercontent.com/4404929/29387321-8d4ff99c-82ad-11e7-8fb0-f467f441d8c1.png)

**Comment by lornajane** [comment]
Closing as these changes have been made
