### ISSUE TITLE
edit question: users with matching tag list should be sorted

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/sodashboard#94]
... by displayed value in ascending order
![bydisplayedvalue](https://user-images.githubusercontent.com/13068832/29998872-d2866b50-8fea-11e7-9f84-13a9d3aa19cc.png)

**Comment by lornajane** [comment]
What's the current sort order (probably question for @vabarbosa)?  I think it's by number of matched tags, which makes more sense than an alphabetical search but perhaps we should have a second search order and/or some indication of how matching someone is.

**Comment by vabarbosa** [comment]
the list is displayed in the order it is received from the db search:

https://github.com/ibm-watson-data-lab/sodashboard/blob/master/public/js/sodashboard.js#L365

PR #109 should resolve this

**Comment by lornajane** [comment]
@ptitzler the results are displayed in order of most-tag-matching person first.  Does that make sense or would you still prefer alphabetical?  I think I like it as is but if it's confusing we can change it.

**Comment by ptitzler** [comment]
Without an indication how much more a given user's expertise matches the question's tags than somebody else's an SO monitor can't really make a more qualified decision given the current output. Let's say a question contains three tags, and there is one person with two matching tags and three people with one matching tag. If the output was as follows it would be clear that there is a sort order and how it was derived.
```
user1 (3 matching tags)
user2 (1 matching tag)
user3 (1 matching tag)
user4 (1 matching tag)
```

**Comment by lornajane** [comment]
@vabarbosa is there a sane way to fetch how matching a user is and display that?  I think @ptitzler's suggestion would work well

**Comment by vabarbosa** [comment]
@ptitzler @lornajane PR #109  has been updated to sort by number of matching tags first then by name and to also show the number of tags matched as indicated in comment above
